spring.application.name=apicrypto
spring.cache.type=caffeine
API.KEY=
# R2DBC URL para banco H2 em memória
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.devtools.restart.enabled=true
spring.devtools.enabled=true
### mail config
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=info
logging.level.com.apicela.apicrypto=DEBUG
logging.level.org.springframework.cache=DEBUG
